### PR TITLE
Add organization of tasks by section

### PR DESCRIPTION
**Pull request by Lillenne**
# Summary
Adds organization of tasks by section to the todoist buffer. 

todoist-fork-demo

# Rationale
My wife and I like to use sections for organizing our shared todoist project since we only use the free tier and would have more than 5 projects. The wall of tasks per project is hard to navigate visually in our scenario.

# Notes
Please feel free to edit or decline if this functionality isn't required or should be hidden behind a flag! I have very little experience writing elisp and I'm certain my implementation isn't optimal, but it gets the job done for me.

### CODE REVIEW

**Comment by abrochard** [comment]
Hi @Lillenne ,
Thank you for submitting this! I had no idea about todoist sections so I'm very pleased to learn about them.

The code looks good enough but I did find a bug while testing? If I have a project with tasks at the root and tasks under a section, tasks at the root do not show up in my buffer. Can you reproduce on your side?

**Comment by Lillenne** [comment]
I was able to reproduce the bug. All of our tasks were sectioned, so sorry I didn't notice that case! I pushed up a fix so now tasks under the project root will show up under an "Unsectioned" heading when there are sections under the project. If there are no sections, all tasks still show up at level 3 like before. 

todoist-fork-unsectioned

**Comment by abrochard** [comment]
Thanks for the fix! I just re-tested and found another side effect, at least on my side: the unsectioned heading gets populated with every task in my inbox, regardless of the project.

**Comment by Lillenne** [comment]
Sorry for giving you so much to test, I should have been more thorough before creating a PR (the original implementation had been working for me since we quickly section everything). Thank you for looking over it! I pushed up another fix and tested the following cases:
- Projects fully sectioned
- Projects with a mix of sectioned & non-sectioned tasks
- Projects with only non-sectioned tasks

and verified that:
- All sectioned tasks & tasks at the root of a project are displayed.
- Inbox tasks (and tasks from any other projects) are not included in the "Unsectioned" tab. I had not filtered the task list per project when inserting here, which was the source of the bug you just found. 

todoist-fork-unsectioned-fixed
image

**Comment by abrochard** [comment]
No worries! I really appreciate your contribution. I just tested on my side again and it looks good!

**Review by abrochard — APPROVED** [review]

**Pull request merged**
